### PR TITLE
add create asset settings method

### PR DESCRIPTION
**Pull request by JHUShanZhong**
POST /assets/:id/settings
{
  settings_ids: ["uuid1", "uuid2", ...]
}

### CODE REVIEW

**Comment by JHUShanZhong** [comment]
@jessica-christie Don't know why the test keeps failing on circleci. It passes on local "go test".

**Comment by jessica-christie** [comment]
@JHUShanZhong please fix circle failure.

**Comment by JHUShanZhong** [comment]
@jessica-christie I think circleci loads github.com/SYNQfm/SYNQ-Golang/test_server from master branch for testing, which causes the mock server not updated and test fails. The only solution to pass circleci test is to merge the server update first then add in test.

**Comment by jessica-christie** [comment]
@JHUShanZhong you're right. Please create a separate PR for the test_server so we can merge it first. Thanks.

**Comment by JHUShanZhong** [comment]
[General : Add create asset settings method in SYNQ-Golang](https://trello.com/c/HkFtzB2c/1109-general-add-create-asset-settings-method-in-synq-golang)

**Comment by jessica-christie** [comment]
Fixed the versioning issue.

**Pull request merged**
