### PR TITLE
change govendor to dep

### PR DESCRIPTION
**Pull request by jessica-christie**

### CODE REVIEW

**Comment by chrisjob** [comment]
Is there an equivalent command to: **govendor install** that should be triggered to install dependencies in local environment(s)?

**Comment by jessica-christie** [comment]
@chrisjob Use the `dep ensure` command.

From https://golang.github.io/dep/docs/daily-dep.html:

```
Using dep ensure
There are four times when you'll run dep ensure:

- To add a new dependency
- To update an existing dependency
- To catch up after importing a package for the first time in your project, or removing the last import of a package in your project
- To catch up to a change to a rule in Gopkg.toml

```

**Comment by chrisjob** [comment]
I see, so could we include this in the readme file?

**Comment by jessica-christie** [comment]
@chrisjob Updated README

**Pull request merged**
