### PR TITLE
account_id should be nil for asset if "" string is passed

### PR DESCRIPTION
**Pull request by fionaDawn**

### CODE REVIEW

**Comment by jessica-christie** [comment]
@fionaDawn Why not just use video.CreateOrUpdateAsset directly ?

**Comment by fionaDawn** [comment]
@jessica-christie i'll reopen this but the change will now just be on the asset struct

**Comment by jessica-christie** [comment]
> @jessica-christie i'll reopen this but the change will now just be on the asset struct

@fionaDawn Why do you want to set it to omitempty?

**Comment by fionaDawn** [comment]
so account_id is null. not ""

**Comment by jessica-christie** [comment]
Why do you need it to be null instead of "" ?
I'm asking because this could affect existing checking for other services.

**Comment by fionaDawn** [comment]
I checked prod db and account_id is either UUID or null as value. Exactly why I want to force it as null. To be consistent with our current setup, which is account_id being null for assets that don't belong to an account.

And since imugi or other microservices in the long run might pass "" as account_id when creating asset but we'd want it to be saved as null if "" is passed. @jessica-christie

**Comment by jessica-christie** [comment]
I sent an asset POST request to akka with account_id set to "", it still returned `account_id: null`.

Also double checked Hydra and it sets account_id to "". If the existing data in the db shows null and not "", then it should be fine as is.

**Comment by fionaDawn** [comment]
ahhh right, akka does check for valid uuid for account_id then sets it as null if blank. since it's in a `belong_to` relationship with account. Nice, i'll close this now. Thanks for your inputs @jessica-christie !

**Pull request closed without merging**
